#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Jan 13, 2019 07:35:41 PM GMT  platform: Windows NT

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global scoreCounterP1
    scoreCounterP1 = StringVar()
    global roundCount
    roundCount = StringVar()

def rollUserOne():
    print('mdc_support.rollUserOne')
    sys.stdout.flush()

def rollUserTwo():
    print('mdc_support.rollUserTwo')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import mdcGUI
    mdcGUI.vp_start_gui()

