#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Jan 07, 2019 05:08:54 PM GMT  platform: Windows NT

import sys
import registerHandler

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global usernameVar
    usernameVar = StringVar()
    global fullNameVar
    fullNameVar = StringVar()
    global emailVar
    emailVar = StringVar()
    global passwordVar
    passwordVar = StringVar()
    global confPasswordVar
    confPasswordVar = StringVar()

def registerUser():
    usrVar = (usernameVar.get())
    pswVar = (passwordVar.get())
    confPswVar = (confPasswordVar.get())
    fnVar = (fullNameVar.get())
    emVar = (emailVar.get())
    registerHandler.newUser(usrVar, pswVar, confPswVar, fnVar, emVar)
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import register
    register.vp_start_gui()

